import { chromium, devices } from 'playwright';
const out = process.env.OUT;
const base = process.env.BASE || 'http://127.0.0.1:8090/app/';
const browser = await chromium.launch({ channel: 'chrome' });
const ctx = await browser.newContext({ ...devices['iPhone 14'], locale: 'ru-RU', deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto(base, { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/app-01-home.png`, fullPage: true });
await page.getByText('Показать на примере').click();
await page.waitForSelector('text=Варианты ставки', { timeout: 90000 });
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/app-02-card-top.png` });
await page.screenshot({ path: `${out}/app-02-card-full.png`, fullPage: true });
await page.getByText('Собрать текст вакансии').click();
await page.waitForSelector('text=Скопировать', { timeout: 30000 });
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/app-03-vacancy-text.png`, fullPage: true });
await page.goto(base, { waitUntil: 'networkidle' });
await page.fill('input[inputmode="numeric"]', '7801633015');
await page.getByText('Найти в реестре МСП').click();
await page.waitForSelector('text=Реестр МСП ФНС', { timeout: 30000 });
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/app-04-profile.png`, fullPage: true });
await page.getByText('Показать рынок').first().click();
await page.waitForSelector('text=Проверить ставку', { timeout: 10000 });
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/app-05-query.png`, fullPage: true });
await browser.close();
console.log('done');
